
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: kzldlgr
  password: postgres

development:
  <<: *default
  database: journal_planner_webpage_development

test:
  <<: *default
  database: journal_planner_webpage_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>